// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { handlers_workspaceProduct } from "../../../../../../../definitions/handlers.workspaceProduct.js";
import type { http_server_BasicResponse } from "../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * Returns a list of products (with ID and name) that are enabled for a specific workspace
 */
export type activationPanelWorkspaceProductsGet = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: activationPanelWorkspaceProductsGet_Path;
    headers: activationPanelWorkspaceProductsGet_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<handlers_workspaceProduct>;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type activationPanelWorkspaceProductsGet_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type activationPanelWorkspaceProductsGet_Headers = {
  /**
   * Semrush-admin Remote-User (UserId)
   */
  "Remote-User": string;
  /**
   * Admin API key
   */
  "API-Key": string;
};
