// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { handlers_SegmentResponse } from "../../../../../../../definitions/handlers.SegmentResponse.js";
import type { http_server_BasicResponse } from "../../../../../../../definitions/http_server.BasicResponse.js";
import type { handlers_SegmentUpsertForm } from "../../../../../../../definitions/handlers.SegmentUpsertForm.js";

/**
 * Gets a segment of a project by id. For description of response fields like conditions and filters,
 * see segment create under **Segment** * /workspaces/{id}/projects/{project_id}/segments [post]*
 */
export type projectSegmentsGet = (
  $: OmitValueWhenNever<{
    query: projectSegmentsGet_Query;
    querystring: never;
    path: projectSegmentsGet_Path;
    headers: projectSegmentsGet_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_SegmentResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * update segment for a project BY id, see segment create for valid conditions and filters fields
 * column_name, operator and value validations.
 */
export type projectSegmentUpdate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: projectSegmentUpdate_Path;
    headers: projectSegmentUpdate_Headers;
    cookie: never;
    body: handlers_SegmentUpsertForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_SegmentResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type projectSegmentsGet_Query = {
  /**
   * whether to show only for live projects
   */
  live?: "true" | "false";
};

export type projectSegmentsGet_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * segment id
   */
  segment_id: string;
};

export type projectSegmentsGet_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type projectSegmentUpdate_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * segment id
   */
  segment_id: string;
};

export type projectSegmentUpdate_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
