// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";

/**
 * This API deletes a product and its tier from a master workspace. If the product is removed from the root workspace, it will only be deleted from the root workspace and not from all workspaces in the system.
 * For non-root workspaces, the product and its tier are automatically deleted from the workspace and its child workspaces.
 * Note: This API can only be used to delete products from master workspaces. Non-master workspaces' products cannot be deleted using this API.
 */
export type adminWorkspaceProductDelete = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: adminWorkspaceProductDelete_Path;
    headers: adminWorkspaceProductDelete_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adminWorkspaceProductDelete_Path = {
  /**
   * Workspace ID (UUID)
   */
  id: string;
  /**
   * Product ID (UUID)
   */
  product_id: string;
};

export type adminWorkspaceProductDelete_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
