// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../counterfact-types/index.ts";
import type { handlers_LogFileAnalysisConnectorStatusPayload } from "../../../../../../../../definitions/handlers.LogFileAnalysisConnectorStatusPayload.js";

/**
 * Persists connector-reported success or error status. Returned on all workspace connection GET endpoints for this connection.
 */
export type internalLogFileAnalysisConnectionStatusPatch = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: internalLogFileAnalysisConnectionStatusPatch_Path;
    headers: internalLogFileAnalysisConnectionStatusPatch_Headers;
    cookie: never;
    body: handlers_LogFileAnalysisConnectorStatusPayload;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type internalLogFileAnalysisConnectionStatusPatch_Path = {
  /**
   * workspace id
   */
  workspace_id: string;
  /**
   * connection id
   */
  connection_id: string;
};

export type internalLogFileAnalysisConnectionStatusPatch_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
