// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../counterfact-types/index.ts";
import type { handlers_BatchDeleteReferenceRequest } from "../../../../../../../../definitions/handlers.BatchDeleteReferenceRequest.js";
import type { http_server_BasicResponse } from "../../../../../../../../definitions/http_server.BasicResponse.js";
import type { handlers_tagsListWithSearchResponse } from "../../../../../../../../definitions/handlers.tagsListWithSearchResponse.js";

/**
 * deletes tags from target in workspace, project with given IDs. This endpoint allows batch operations for removing tag.
 */
export type projectDeleteTagsBatchV2 = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: projectDeleteTagsBatchV2_Path;
    headers: projectDeleteTagsBatchV2_Headers;
    cookie: never;
    body: handlers_BatchDeleteReferenceRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * API to return list of all tags that belong to a target
 * parent_id param can be used to get tags with specific parent
 * query param can be used to filter tags by name
 * live flag can be used get live/draft target's tags
 * use limit, page for paginated result
 */
export type projectGetTagsWithSearch = (
  $: OmitValueWhenNever<{
    query: projectGetTagsWithSearch_Query;
    querystring: never;
    path: projectGetTagsWithSearch_Path;
    headers: projectGetTagsWithSearch_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_tagsListWithSearchResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type projectDeleteTagsBatchV2_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * target id
   */
  target_id: string;
};

export type projectDeleteTagsBatchV2_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type projectGetTagsWithSearch_Query = {
  /**
   * page number
   */
  page?: number;
  /**
   * page size
   */
  limit?: number;
  /**
   * parent id
   */
  parent_id?: string;
  /**
   * search query
   */
  query?: string;
  /**
   * live
   */
  live?: boolean;
};

export type projectGetTagsWithSearch_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * target id
   */
  target_id: string;
};

export type projectGetTagsWithSearch_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
