// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { page_engine_backend_internal_usermanager_core_domain_InternalProjectV2List } from "../../../../../definitions/page-engine-backend_internal_usermanager_core_domain.InternalProjectV2List.js";
import type { http_server_BasicResponse } from "../../../../../definitions/http_server.BasicResponse.js";

/**
 * This endpoint retrieves a list of projects available in a specific workspace.
 * It allows filtering of projects based on user access roles or permissions.
 * Only those projects are returned where the user has access.
 * User roles and permissions are determined by the following rules:
 * - Workspace Owners, Admins, and Editors have editor-level access to all projects in the workspace.
 * - Workspace Viewers are granted view-level access to all projects in the workspace.
 * - Specific roles, such as collaborators or content writers, control project-level access.
 * Use query parameters to refine the results, including user ID and pagination options.
 */
export type internalProjectsListV2 = (
  $: OmitValueWhenNever<{
    query: internalProjectsListV2_Query;
    querystring: never;
    path: internalProjectsListV2_Path;
    headers: internalProjectsListV2_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: page_engine_backend_internal_usermanager_core_domain_InternalProjectV2List;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type internalProjectsListV2_Query = {
  /**
   * user id
   */
  user_id?: number;
  /**
   * search by project name
   */
  search?: string;
  /**
   * page number
   */
  page?: number;
  /**
   * page size
   */
  limit?: number;
};

export type internalProjectsListV2_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type internalProjectsListV2_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
