// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_workspaceUpdateIconForm } from "../../../../definitions/handlers.workspaceUpdateIconForm.js";

/**
 * Validates the Ed25519-signed receipt from the upload service, then stores the icon URL.
 */
export type workspaceUpdateIcon = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: workspaceUpdateIcon_Path;
    headers: workspaceUpdateIcon_Headers;
    cookie: never;
    body: handlers_workspaceUpdateIconForm;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type workspaceUpdateIcon_Path = {
  /**
   * Workspace UUID
   */
  id: string;
};

export type workspaceUpdateIcon_Headers = {
  /**
   * Signed upload receipt token
   */
  "X-Upload-Receipt": string;
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
