// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_KeywordsListDeleteRequest } from "../../../../definitions/handlers.KeywordsListDeleteRequest.js";
import type { http_server_BasicResponse } from "../../../../definitions/http_server.BasicResponse.js";
import type { handlers_KeywordsListResponse } from "../../../../definitions/handlers.KeywordsListResponse.js";
import type { handlers_KeywordsListCreateRequest } from "../../../../definitions/handlers.KeywordsListCreateRequest.js";
import type { handlers_KeywordsListCreateResponse } from "../../../../definitions/handlers.KeywordsListCreateResponse.js";

/**
 * delete keywords-lists of a workspace by basket ids
 */
export type keywordslistsDelete = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: keywordslistsDelete_Path;
    headers: keywordslistsDelete_Headers;
    cookie: never;
    body: handlers_KeywordsListDeleteRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Gets list of keywords-lists for the workspace. Pagination is not supported for now.
 */
export type keywordslistsGet = (
  $: OmitValueWhenNever<{
    query: keywordslistsGet_Query;
    querystring: never;
    path: keywordslistsGet_Path;
    headers: keywordslistsGet_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_KeywordsListResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Create a keywords-list for the workspace
 */
export type keywordslistsPost = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: keywordslistsPost_Path;
    headers: keywordslistsPost_Headers;
    cookie: never;
    body: handlers_KeywordsListCreateRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_KeywordsListCreateResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type keywordslistsDelete_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type keywordslistsDelete_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type keywordslistsGet_Query = {
  /**
   * field default: name
   */
  field?: "name" | "updated_at";
  /**
   * sort direction, default:asc
   */
  direction?: "asc" | "desc";
  /**
   * search by keyword list name
   */
  search?: string;
};

export type keywordslistsGet_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type keywordslistsGet_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type keywordslistsPost_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type keywordslistsPost_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
