// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_workspaceDeleteMembersForm } from "../../../../definitions/handlers.workspaceDeleteMembersForm.js";
import type { handlers_WorkspaceMemberUpsertResponse } from "../../../../definitions/handlers.WorkspaceMemberUpsertResponse.js";
import type { http_server_BasicResponse } from "../../../../definitions/http_server.BasicResponse.js";
import type { handlers_workspacesMembersResponse } from "../../../../definitions/handlers.workspacesMembersResponse.js";
import type { handlers_workspaceMemberUpdateRoleForm } from "../../../../definitions/handlers.workspaceMemberUpdateRoleForm.js";
import type { handlers_workspaceAddMembersForm } from "../../../../definitions/handlers.workspaceAddMembersForm.js";
import type { handlers_workspaceAddMembersResponse } from "../../../../definitions/handlers.workspaceAddMembersResponse.js";

/**
 * deletes members of a workspace
 * in response it returns number of user units freed,
 * +ve value means workspace user units are credited back and users are removed from corporate account.
 * 0 values mean user units are not changed and corporate account remains unaffected.
 */
export type workspaceDeleteMembers = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: workspaceDeleteMembers_Path;
    headers: workspaceDeleteMembers_Headers;
    cookie: never;
    body: handlers_workspaceDeleteMembersForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_WorkspaceMemberUpsertResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * gets a workspace's members
 * **Note:** Users with roles *Collaborator* or *Content Writer* will receive **no members** in the response (an empty list), regardless of workspace membership.
 */
export type workspacesMembers = (
  $: OmitValueWhenNever<{
    query: workspacesMembers_Query;
    querystring: never;
    path: workspacesMembers_Path;
    headers: workspacesMembers_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspacesMembersResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Updates a member's role in workspaces by promoting/demoting user in the workspace.
 * in response it returns number of user units consumed/freed,
 * +ve value means workspace user units are credited back and user is removed from corporate account.
 * -ve value means workspace user units are consumed and user is invited to corporate account.
 * 0 values mean user units are not changed and corporate account remains unaffected.
 */
export type workspacesMembersUpdate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: workspacesMembersUpdate_Path;
    headers: workspacesMembersUpdate_Headers;
    cookie: never;
    body: handlers_workspaceMemberUpdateRoleForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_WorkspaceMemberUpsertResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * adds members to a workspace and assigns them a specific role
 * in response it returns number of user units consumed
 * -ve value means workspace user units are consumed and users are invited to corporate account.
 * 0 values mean user units are not changed and corporate account remains unaffected.
 * **Note**: External users (without @semrsuh.com email) cannot be invited to Semrush workspaces.
 */
export type workspaceAddMembers = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: workspaceAddMembers_Path;
    headers: workspaceAddMembers_Headers;
    cookie: never;
    body: handlers_workspaceAddMembersForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_WorkspaceMemberUpsertResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceAddMembersResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceAddMembersResponse;
          };
        };
        examples: {};
      };
      422: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceAddMembersResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceAddMembersResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type workspaceDeleteMembers_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type workspaceDeleteMembers_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type workspacesMembers_Query = {
  /**
   * page number
   */
  page?: number;
  /**
   * page size
   */
  limit?: number;
  /**
   * asc/desc
   */
  direction?: string;
  /**
   * search by email
   */
  search?: string;
  /**
   * search by role name
   */
  role?: string;
  /**
   * search by membership status
   */
  membership_status?: string;
  /**
   * include parental admins
   */
  include_parental_admins?: boolean;
  /**
   * include parent workspace
   */
  include_parent_workspace?: boolean;
};

export type workspacesMembers_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type workspacesMembers_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type workspacesMembersUpdate_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type workspacesMembersUpdate_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type workspaceAddMembers_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type workspaceAddMembers_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
