import type { page_engine_backend_internal_usermanager_core_domain_WorkspaceParent } from "./page-engine-backend_internal_usermanager_core_domain.WorkspaceParent.js";
import type { page_engine_backend_internal_usermanager_core_domain_ProductTier } from "./page-engine-backend_internal_usermanager_core_domain.ProductTier.js";
import type { page_engine_backend_internal_usermanager_core_domain_ProductID } from "./page-engine-backend_internal_usermanager_core_domain.ProductID.js";
import type { handlers_workspaceSettings } from "./handlers.workspaceSettings.js";
import type { page_engine_backend_internal_usermanager_core_domain_Tier } from "./page-engine-backend_internal_usermanager_core_domain.Tier.js";

export type handlers_workspaceV2Response = {
  created_at?: string;
  expires_at?: string;
  icon?: string;
  id?: string;
  is_admin?: boolean;
  is_master?: boolean;
  keywords_count?: number;
  last_updated_at?: string;
  owner?: string;
  pagespeed_urls_count?: number;
  parent?: page_engine_backend_internal_usermanager_core_domain_WorkspaceParent;
  parent_id?: string;
  partnership_enabled?: boolean;
  product_tiers?: Array<page_engine_backend_internal_usermanager_core_domain_ProductTier>;
  products?: Array<page_engine_backend_internal_usermanager_core_domain_ProductID>;
  published_projects_count?: number;
  resources?: { [key: string]: { [key: string]: unknown } };
  role?: string;
  settings?: handlers_workspaceSettings;
  shared_with?: number;
  status?: string;
  subscription_tier?: page_engine_backend_internal_usermanager_core_domain_Tier;
  title?: string;
  users?: number;
};
