// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { handlers_SegmentUpsertForm } from "../../../../../definitions/handlers.SegmentUpsertForm.js";
import type { handlers_SegmentResponse } from "../../../../../definitions/handlers.SegmentResponse.js";
import type { http_server_BasicResponse } from "../../../../../definitions/http_server.BasicResponse.js";

/**
 * creates a new segment in a specified project
 * **<u>conditions :</u>**
 * `column_name` is one of *url, url_list, keyword, keyword_list, traffic, position, search_volume,
 * keyword_intent, country, device, clicks, impressions, ctr, gsc_position*
 * `operator` is one of *equal, not_equal, begin, not_begin, end, not_end, contain,
 * not_contain, greater, less, greater_equal, less_equal, between, one_of, in_list*
 * *url_list* only can be used with *in_list* operator. Only zero or one url_list is allowed in the whole conditions array.
 * *keyword_list* only can be used with *in_list* operator.
 * **<u>filters :</u>**
 * `column_name` is one of *url, url_list, keyword, keyword_list, traffic, position, search_volume,
 * keyword_intent, country, device, clicks, impressions, ctr, gsc_position*.
 * `operator` is one of *and, or, equal, not_equal, begin, not_begin, end, not_end, contain,
 * not_contain, greater, less, greater_equal, less_equal, in_list*.
 * `value` is string type. It becomes array of string in case of *in_list* operator as an exceptional case.
 * *Notes*:
 * * *url_list* only can be used with *in_list* operator. Only zero or one url_list is allowed in the whole filters array.
 * * *keyword_list* only can be used with *in_list* operator.
 * * *filters* logical operators *and, or* don't have *column_name, value* and must have nested *filters*.
 * * *filters* logical operators *and, or* can have maximum depth up to 5 levels from the root.
 * * *filters* non-logical operators must have *column_name, value* and must not have nested *filters*.
 * * *filters* non-logical operators can have maximum 20 leaves in a single filter object.
 */
export type projectSegmentCreate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: projectSegmentCreate_Path;
    headers: projectSegmentCreate_Headers;
    cookie: never;
    body: handlers_SegmentUpsertForm;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_SegmentResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type projectSegmentCreate_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
};

export type projectSegmentCreate_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
