# generated by datamodel-codegen:
#   filename:  openapi3.json
#   timestamp: 2026-07-03T09:18:30+00:00

from __future__ import annotations

from pydantic import BaseModel


class BrandTopicWithPrompts(BaseModel):
    prompts: list[str] | None = None
    topic: str | None = None
    volume: int | None = None
