# generated by datamodel-codegen:
#   filename:  openapi3.json
#   timestamp: 2026-06-22T14:25:03+00:00

from __future__ import annotations

from pydantic import BaseModel


class BrandTopicWithPrompts(BaseModel):
    prompts: list[str] | None = None
    topic: str | None = None
    volume: int | None = None
