# generated by datamodel-codegen:
#   filename:  openapi3.json
#   timestamp: 2026-07-06T06:16:27+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, constr


class AIModelResponse(BaseModel):
    icon: str | None = None
    id: str
    key: str | None = None
    name: str | None = None


class AIOBenchmarkRequest(BaseModel):
    brand_aliases: list[str] | None = None
    brand_name: str | None = None
    color: str | None = None
    domain: str | None = None
    favorite: bool | None = None
    main_brand: bool | None = None
    primary_url: str | None = None


class AIOBenchmarkWithCounters(BaseModel):
    brand_aliases: list[str] | None = None
    brand_name: str | None = None
    color: str | None = None
    domain: str | None = None
    favorite: bool | None = None
    id: str
    main_brand: bool | None = None
    primary_url: str | None = None
    product_names: list[str] | None = None
    products_count: int | None = None
    project_id: str | None = None
    rejected_brand_aliases: list[str] | None = None
    root_domain: str | None = None


class AIOProduct(BaseModel):
    aliases: list[str] | None = None
    name: str | None = None
    rejected_aliases: list[str] | None = None


class AIOProductEntity(BaseModel):
    aliases: list[str] | None = None
    id: str | None = None
    name: str | None = None
    rejected_aliases: list[str] | None = None


class AIOProjectInitializedResponse(BaseModel):
    initialized: bool | None = None


class AIOPromptsListRequest(BaseModel):
    limit: int | None = None
    page: int | None = None
    search: str | None = None
    sort_dir: str | None = None
    sort_field: str | None = None
    tag_ids: list[str] | None = None
    unassigned: bool | None = None


class AIOTagLeaf(BaseModel):
    id: str | None = None
    name: str | None = None
    parent_id: str | None = None


class AIOTaggedPromptsCreateRequest(BaseModel):
    prompts: dict[str, list[str]] | None = None


class AdvancedCrawlingConsentRequest(BaseModel):
    accepted: bool
    confirmed_at: str
    confirmed_by_email: str
    confirmed_by_name: str


class AdvancedCrawlingConsentResponse(BaseModel):
    accepted: bool | None = None
    confirmed_at: str | None = None
    confirmed_by_email: str | None = None
    confirmed_by_name: str | None = None


class MatchBy(Enum):
    one_shot_rule = 'one_shot_rule'
    issue_id = 'issue_id'


class ApplyInteractiveIgnoreIssueRulesRequest(BaseModel):
    issue_ids: list[str]
    issue_type: str
    match_by: MatchBy
    recent_check: int | None = None


class AvailablePromptsResponse(BaseModel):
    available: int | None = None
    total: int | None = None


class BatchDeleteRequest(BaseModel):
    all: bool | None = None
    cascade: bool | None = None
    ids: list[str]


class BrandURL(BaseModel):
    benchmark_id: str | None = None
    created_at: str | None = None
    id: str
    project_id: str | None = None
    type: str | None = None
    updated_at: str | None = None
    url: str | None = None


class BrandURLRequest(BaseModel):
    type: constr(max_length=32) | None = None
    url: str


class BulkCreateAIOProjectsErrorItem(BaseModel):
    message: str | None = None
    row_index: int | None = None


class BulkCreateAIOProjectsErrorResponse(BaseModel):
    errors: list[BulkCreateAIOProjectsErrorItem] | None = None


class BulkCreateAIOProjectsLimitInfoResponse(BaseModel):
    available: int | None = None
    max: int | None = None
    requested: int | None = None


class BulkCreateAIOProjectsLimitsResponse(BaseModel):
    can_create: bool | None = None
    projects: BulkCreateAIOProjectsLimitInfoResponse | None = None
    prompts: BulkCreateAIOProjectsLimitInfoResponse | None = None


class BulkCreateAIOProjectsPublishedItem(BaseModel):
    project_id: str | None = None
    row_index: int | None = None


class BulkCreateAIOProjectsResponseItem(BaseModel):
    created_ai_model_ids: list[str] | None = None
    project_id: str | None = None
    prompt_count: int | None = None
    row_index: int | None = None


class BulkCreateAIOProjectsUnpublishedItem(BaseModel):
    project_id: str | None = None
    reason: str | None = None
    row_index: int | None = None


class CICompetitor(BaseModel):
    color: str | None = None
    domain: str | None = None
    id: str | None = None
    project_id: str | None = None


class CICompetitorsResponse(BaseModel):
    ci_competitors: list[CICompetitor] | None = None


class CICompetitorsUpdateRequest(BaseModel):
    ci_competitors: list[CICompetitor] | None = None


class CICountriesResponse(BaseModel):
    ci_countries: list[str] | None = None


class CICountriesUpdateRequest(BaseModel):
    ci_countries: list[str] | None = None


class CISettings(BaseModel):
    competitors: list[CICompetitor] | None = None
    countries: list[str] | None = None
    segments_count: int | None = None


class CopyAllSegmentsRequest(BaseModel):
    source_project_id: str


class CopySegmentsRequest(BaseModel):
    segment_ids: list[str] = Field(..., min_length=1)
    target_project_ids: list[str] = Field(..., min_length=1)


class CountryResponse(BaseModel):
    code: str | None = None
    name: str | None = None


class AnalysisDevice(Enum):
    desktop = 'desktop'
    mobile = 'mobile'
    tablet = 'tablet'


class CrawlerScheduleRequest(BaseModel):
    frequency: str
    start_day: str | None = None
    start_time: str


class CrawlerScheduleResponse(BaseModel):
    frequency: str | None = None
    start_day: str | None = None
    start_time: str | None = None


class CrawlerStats(BaseModel):
    device: str | None = None
    location: CountryResponse | None = None


class CrawlerUrlRuleRequest(BaseModel):
    dimension: str
    operator: str
    type: str
    value: str


class CrawlerUrlRuleResponse(BaseModel):
    dimension: str | None = None
    operator: str | None = None
    type: str | None = None
    value: str | None = None


class CreateAIOProductsResponse(BaseModel):
    products: list[AIOProductEntity] | None = None


class CreateProjectAIModelRequest(BaseModel):
    model_id: str


class Mode(Enum):
    xpath_get_complete_tag = 'xpath_get_complete_tag'
    xpath_get_text_only = 'xpath_get_text_only'
    css_get_text_only = 'css_get_text_only'
    css_get_complete_tag = 'css_get_complete_tag'
    regex_search_in_text = 'regex_search_in_text'
    regex_search_in_html = 'regex_search_in_html'


class Type(Enum):
    field = 'field'
    counter = 'counter'


class CustomExtractionRequest(BaseModel):
    additional_info: str | None = None
    id: str | None = None
    mode: Mode
    name: str
    nr: int | None = None
    project_id: str | None = None
    selector: str
    type: Type


class CustomExtractionResponse(BaseModel):
    additional_info: str | None = None
    created_at: str | None = None
    id: str | None = None
    mode: str | None = None
    name: str | None = None
    nr: int | None = None
    project_id: str | None = None
    selector: str | None = None
    type: str | None = None


class CustomExtractionsListResponse(BaseModel):
    items: list[CustomExtractionResponse] | None = None
    page: int | None = None
    total: int | None = None


class DeleteAIOProductsRequest(BaseModel):
    ids: list[str]


class ExistingKeywordsCountResponse(BaseModel):
    existing_count: int | None = None


class FilterRequest(BaseModel):
    column_name: str | None = None
    filters: list[FilterRequest] | None = None
    value: Any | None = None


class FilterResponse(BaseModel):
    column_name: str | None = None
    filters: list[FilterResponse] | None = None
    value: Any | None = None


class IDsWithStatsResponse(BaseModel):
    existing_count: int | None = None
    ids: list[str] | None = None


class ImportPromptsRequest(BaseModel):
    prompt_ids: list[str] | None = None
    source_model_id: str
    source_project_id: str
    source_workspace_id: str
    tag_ids: list[str] | None = None


class IssueRulesRequest(BaseModel):
    filters: FilterRequest
    id: str | None = None
    name: str


class IssueRulesResponse(BaseModel):
    created_at: str | None = None
    filters: FilterResponse | None = None
    id: str | None = None
    name: str | None = None
    project_id: str | None = None


class KeywordRequest(BaseModel):
    items: list[str] | None = None
    tag_ids: list[str] | None = None


class KeywordsByTagIDsRequest(BaseModel):
    include_tags: int | None = None
    limit: int | None = None
    page: int | None = None
    search: str | None = None
    sort_dir: str | None = None
    tag_ids: list[str] | None = None
    unassigned: bool | None = None


class KeywordsTaggedRequest(BaseModel):
    keywords: dict[str, list[str]] | None = Field(
        None, description='TODO: LJ: Validate'
    )


class LanguageResponse(BaseModel):
    id: str | None = None
    name: str | None = None


class ListAIOBenchmarksResponse(BaseModel):
    aio_benchmarks: list[AIOBenchmarkWithCounters] | None = None


class ListAIOProductsResponse(BaseModel):
    items: list[AIOProductEntity] | None = None
    page: int | None = None
    total: int | None = None


class ListBrandURLsResponse(BaseModel):
    brand_urls: list[BrandURL] | None = None


class LocationResponse(BaseModel):
    id: int | None = None
    name: str | None = None


class ManagedAIModelsResponse(BaseModel):
    managed_ai_models: dict[str, bool] | None = None


class ProjectAIModelResponse(BaseModel):
    id: str
    model: AIModelResponse
    prompts_count: int


class ProjectModelStats(BaseModel):
    models: list[ProjectAIModelResponse] | None = None
    models_count: int | None = None


class TypeModel(Enum):
    SEO = 'SEO'
    AI = 'AI'
    MFOUR = 'MFOUR'
    SI = 'SI'
    CI = 'CI'
    seo = 'seo'
    ai = 'ai'
    mfour = 'mfour'
    si = 'si'
    ci = 'ci'


class ProjectRequest(BaseModel):
    brand_name_display: str | None = None
    brand_names: list[str] | None = None
    color: str | None = None
    country_code: str | None = None
    domain: str | None = None
    language_id: str | None = None
    location_id: int | None = None
    location_name: str | None = None
    name: str
    primary_url: str | None = None
    type: TypeModel = Field(..., description='enum: seo, ai, mfour, si, ci')


class TypeModel1(Enum):
    AI = 'AI'
    MFOUR = 'MFOUR'
    SI = 'SI'
    CI = 'CI'
    ai = 'ai'
    mfour = 'mfour'
    si = 'si'
    ci = 'ci'


class ProjectUpdateRequest(BaseModel):
    brand_name_display: str | None = None
    brand_names: list[str] | None = None
    color: str | None = None
    country_code: str | None = None
    domain: str | None = None
    language_id: str | None = None
    location_id: int | None = None
    location_name: str | None = None
    name: str | None = None
    primary_url: str | None = None
    type: TypeModel1 = Field(..., description='enum: ai, mfour, si')


class ReferenceRequest(BaseModel):
    id: str
    references: list[str] = Field(..., min_length=1)
    replace: bool | None = None


class RenamePromptRequest(BaseModel):
    new_name: str | None = None


class RenamePromptResponse(BaseModel):
    id: str | None = None
    is_updated: bool | None = None
    name: str | None = None


class ReplaceModelSettingsRequest(BaseModel):
    ids: list[str]


class ResolveLocationsRequest(BaseModel):
    locations: list[str] = Field(..., min_length=1)


class ResolveLocationsResponseItem(BaseModel):
    country_code: str | None = None
    location_name: str | None = None
    status: str | None = None


class ResolveURLResponse(BaseModel):
    domain: str
    is_valid: bool
    primary_url: str


class RestorePromptNamesRequest(BaseModel):
    ids: list[str] = Field(..., min_length=1)


class RestorePromptNamesResponse(BaseModel):
    restored_ids: list[str] | None = None


class Behaviour(Enum):
    analyse_all_custom_robots_stats = 'analyse_all_custom_robots_stats'
    analyse_all_site_robots_stats = 'analyse_all_site_robots_stats'
    respect_site_robots_txt = 'respect_site_robots_txt'
    respect_custom_robots_txt = 'respect_custom_robots_txt'


class RobotsTxtBehaviourRequest(BaseModel):
    behaviour: Behaviour
    custom_robots_txt: str | None = None


class RobotsTxtBehaviourResponse(BaseModel):
    behaviour: str | None = None
    custom_robots_txt: str | None = None


class SISettings(BaseModel):
    advanced_crawling_consent: AdvancedCrawlingConsentResponse | None = None
    crawler_stats: list[CrawlerStats] | None = None
    crawlers_count: int | None = None
    extractions_count: int | None = None
    pages_count: int | None = None
    rules_count: int | None = None
    segments_count: int | None = None


class SegmentsRequest(BaseModel):
    filters: FilterRequest
    name: str


class SegmentsResponse(BaseModel):
    filters: FilterResponse | None = None
    id: str | None = None
    name: str | None = None
    project_id: str | None = None


class SetFavouriteRequest(BaseModel):
    favourite: bool | None = None


class StopCrawlRequest(BaseModel):
    crawl_configuration_id: str
    project_id: str


class StringIDName(BaseModel):
    id: str | None = None
    name: str | None = None


class StringIDNameListResponse(BaseModel):
    items: list[StringIDName] | None = None
    page: int | None = None
    total: int | None = None
    existing_count: int | None = None


class TreeNodeListRequest(BaseModel):
    names: list[str]
    parent_id: str | None = None


class TreeNodeRequest(BaseModel):
    name: str
    parent_id: str | None = None


class TreeNodeResponse(BaseModel):
    children_count: int | None = None
    id: str | None = None
    keyword_count: int | None = None
    name: str | None = None
    parent_id: str | None = None


class UUIDResponse(BaseModel):
    id: str | None = None


class UUIDsListRequest(BaseModel):
    ids: list[str]


class AIModelListResponse(BaseModel):
    page: int | None = None
    total: int | None = None
    items: list[AIModelResponse] | None = None


class AIOTag(BaseModel):
    children_count: int | None = None
    id: str
    name: str | None = None
    parent_id: str | None = None
    path: list[AIOTagLeaf] | None = None
    prompts_count: int | None = None


class AIOTagsListResponse(BaseModel):
    items: list[AIOTag] | None = None
    page: int | None = None
    total: int | None = None


class AISettings(BaseModel):
    benchmarks_count: int | None = None
    brand_name_display: str | None = None
    brand_names: list[str] | None = None
    country: CountryResponse | None = None
    language: LanguageResponse | None = None
    location: LocationResponse | None = None
    models_stats: ProjectModelStats | None = None
    primary_url: str | None = None
    products_count: int | None = None
    prompts_count: int | None = None
    segments_count: int | None = None


class BatchReferenceRequest(BaseModel):
    items: list[ReferenceRequest] = Field(..., min_length=1)


class BulkCreateAIOProjectsResponse(BaseModel):
    projects: list[BulkCreateAIOProjectsResponseItem] | None = None
    published_projects: list[BulkCreateAIOProjectsPublishedItem] | None = None
    unpublished_projects: list[BulkCreateAIOProjectsUnpublishedItem] | None = None


class CountryListResponse(BaseModel):
    items: list[CountryResponse] | None = None
    page: int | None = None
    total: int | None = None


class CrawlerConfigurationCreateRequest(BaseModel):
    analysis_device: AnalysisDevice
    analysis_speed: int
    analyze_shadow_dom: bool | None = None
    analyze_sitemap_xml: bool | None = None
    analyze_subdomains: bool | None = None
    budget: int
    custom_user_agent: str | None = None
    entry_point: str | None = None
    htaccess_login: str | None = None
    htaccess_password: str | None = None
    ignore_get_parameters: str | None = None
    js_rendering: bool | None = None
    location: str
    name: str
    no_adding_extracted_urls_to_queue: bool | None = None
    robots_txt_behaviour: RobotsTxtBehaviourRequest
    schedule: CrawlerScheduleRequest | None = None
    show_in_dashboard: bool | None = None
    sitemap_urls: list[str] | None = None
    start_urls: list[str] | None = None
    subfolder: str | None = None
    url_rules: list[CrawlerUrlRuleRequest] | None = None
    use_multi_start_urls: bool | None = None
    user_agent: str


class CrawlerConfigurationListItemResponse(BaseModel):
    analysis_device: str | None = None
    analysis_speed: int | None = None
    budget: int | None = None
    custom_user_agent: str | None = None
    id: str | None = None
    js_rendering: bool | None = None
    location: str | None = None
    name: str | None = None
    project_id: str | None = None
    publish_status: str | None = None
    schedule: CrawlerScheduleResponse | None = None
    show_in_dashboard: bool | None = None
    use_multi_start_urls: bool | None = None
    user_agent: str | None = None


class CrawlerConfigurationResponse(BaseModel):
    analysis_device: str | None = None
    analysis_speed: int | None = None
    analyze_shadow_dom: bool | None = None
    analyze_sitemap_xml: bool | None = None
    analyze_subdomains: bool | None = None
    budget: int | None = None
    custom_user_agent: str | None = None
    entry_point: str | None = None
    htaccess_login: str | None = None
    htaccess_password: str | None = None
    id: str | None = None
    ignore_get_parameters: str | None = None
    js_rendering: bool | None = None
    location: str | None = None
    name: str | None = None
    no_adding_extracted_urls_to_queue: bool | None = None
    project_id: str | None = None
    publish_status: str | None = None
    published_at: str | None = None
    publishing_failed_reason: str | None = None
    robots_txt_behaviour: RobotsTxtBehaviourResponse | None = None
    schedule: CrawlerScheduleResponse | None = None
    show_in_dashboard: bool | None = None
    sitemap_urls: list[str] | None = None
    start_urls: list[str] | None = None
    subfolder: str | None = None
    url_rules: list[CrawlerUrlRuleResponse] | None = None
    use_multi_start_urls: bool | None = None
    user_agent: str | None = None


class CrawlerConfigurationUpdateRequestSwagger(BaseModel):
    analysis_device: str | None = None
    analysis_speed: int | None = None
    analyze_shadow_dom: bool | None = None
    analyze_sitemap_xml: bool | None = None
    analyze_subdomains: bool | None = None
    budget: int | None = None
    custom_user_agent: str | None = None
    entry_point: str | None = None
    htaccess_login: str | None = None
    htaccess_password: str | None = None
    id: str
    ignore_get_parameters: str | None = None
    js_rendering: bool | None = None
    location: str | None = None
    name: str | None = None
    no_adding_extracted_urls_to_queue: bool | None = None
    project_id: str
    robots_txt_behaviour: RobotsTxtBehaviourRequest | None = None
    schedule: CrawlerScheduleRequest | None = None
    show_in_dashboard: bool | None = None
    sitemap_urls: list[str] | None = None
    start_urls: list[str] | None = None
    subfolder: str | None = None
    url_rules: list[CrawlerUrlRuleRequest] | None = None
    use_multi_start_urls: bool | None = None
    user_agent: str | None = None


class CrawlerConfigurationsListResponse(BaseModel):
    items: list[CrawlerConfigurationListItemResponse] | None = None
    page: int | None = None
    total: int | None = None


class IssueRulesListResponse(BaseModel):
    items: list[IssueRulesResponse] | None = None
    page: int | None = None
    total: int | None = None


class LanguageListResponse(BaseModel):
    items: list[LanguageResponse] | None = None
    page: int | None = None
    total: int | None = None


class ProjectAIModelListResponse(BaseModel):
    items: list[ProjectAIModelResponse] | None = None
    page: int | None = None
    total: int | None = None


class ResolveLocationsResponse(BaseModel):
    results: dict[str, ResolveLocationsResponseItem] | None = None


class SegmentsListResponse(BaseModel):
    items: list[SegmentsResponse] | None = None
    page: int | None = None
    total: int | None = None


class Settings(BaseModel):
    ai: AISettings | None = None
    ci: CISettings | None = None
    si: SISettings | None = None


class TreeNodeListResponse(BaseModel):
    items: list[TreeNodeResponse] | None = None
    page: int | None = None
    total: int | None = None


class AIOPromptWithStatus(BaseModel):
    id: str
    is_new: bool | None = None
    name: str
    tags: list[AIOTag]


class AIOPromptsWithStatusListResponse(BaseModel):
    items: list[AIOPromptWithStatus] | None = None
    page: int | None = None
    total: int | None = None
    unassigned: int | None = None


class KeywordResponse(BaseModel):
    id: str | None = None
    name: str | None = None
    tags: TreeNodeListResponse | None = None


class ProjectResponse(BaseModel):
    color: str | None = None
    domain: str | None = None
    draft_id: str | None = None
    favourite: bool | None = None
    id: str
    is_draft: bool | None = None
    live_id: str | None = None
    name: str
    publish_status: str | None = Field(
        None,
        description='enum: draft, publishing, initial_publish_failed, live, live_with_unpublished_updates',
    )
    published_at: str | None = None
    publishing_failed_reason: str | None = None
    role: str | None = Field(
        None, description='role/project/viewer or role/project/editor'
    )
    settings: Settings | None = None
    shared_with: int | None = None
    type: str | None = Field(None, description='enum: aio,mfour,ci')
    updated_at: str | None = None


class ProjectV2Response(BaseModel):
    color: str | None = None
    domain: str | None = None
    draft_id: str | None = None
    favourite: bool | None = None
    id: str | None = None
    is_draft: bool | None = None
    live_id: str | None = None
    name: str | None = None
    publish_status: str | None = Field(
        None,
        description='enum: draft, publishing, initial_publish_failed, live, live_with_unpublished_updates',
    )
    published_at: str | None = None
    publishing_failed_reason: str | None = None
    role: str | None = None
    settings: Settings | None = None
    shared_with: int | None = None
    type: str | None = Field(None, description='enum: aio,mfour,ci,seo,si')
    updated_at: str | None = None


class KeywordListResponse(BaseModel):
    all_total: int | None = None
    items: list[KeywordResponse] | None = None
    page: int | None = None
    total: int | None = None
    unassigned: int | None = None


class ProjectListResponse(BaseModel):
    items: list[ProjectResponse] | None = None
    page: int | None = None
    total: int | None = None


class ProjectListWithCursorResponse(BaseModel):
    items: list[ProjectResponse] | None = Field(None, description='List of projects')
    next_cursor: str | None = Field(
        None,
        description='Base64 encoded cursor for next page pagination',
        examples=['eyJTRU9PZmZzZXQiOjI1LCJBSU9PZmZzZXQiOjE1fQ=='],
    )
    total: int | None = Field(
        None,
        description='Total number of projects matching the filter criteria',
        examples=[150],
    )


class ProjectV2ListResponse(BaseModel):
    items: list[ProjectV2Response] | None = None
    page: int | None = None
    total: int | None = None


FilterRequest.model_rebuild()
FilterResponse.model_rebuild()
