// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { handlers_goalImportForm } from "../../../../../../../definitions/handlers.goalImportForm.js";
import type { handlers_goalImportReponse } from "../../../../../../../definitions/handlers.goalImportReponse.js";
import type { http_server_BasicResponse } from "../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * this API imports goals from a project to another
 */
export type goalSimport = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: goalSimport_Path;
    headers: goalSimport_Headers;
    cookie: never;
    body: handlers_goalImportForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_goalImportReponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type goalSimport_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
};

export type goalSimport_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
