// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { handlers_keywordsListDeleteMembersForm } from "../../../../../../definitions/handlers.keywordsListDeleteMembersForm.js";
import type { handlers_keywordsListMembersResponse } from "../../../../../../definitions/handlers.keywordsListMembersResponse.js";
import type { http_server_BasicResponse } from "../../../../../../definitions/http_server.BasicResponse.js";
import type { handlers_keywordsListMemberUpdateRoleForm } from "../../../../../../definitions/handlers.keywordsListMemberUpdateRoleForm.js";
import type { handlers_keywordListAddMembersForm } from "../../../../../../definitions/handlers.keywordListAddMembersForm.js";

/**
 * deletes members of a keywords-list
 * Note: External users on Semrush workspace keywords lists are not allowed to be invited
 */
export type keywordsListDeleteMembers = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: keywordsListDeleteMembers_Path;
    headers: keywordsListDeleteMembers_Headers;
    cookie: never;
    body: handlers_keywordsListDeleteMembersForm;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * gets a keywords list members
 */
export type keywordsListMembers = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: keywordsListMembers_Path;
    headers: keywordsListMembers_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_keywordsListMembersResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * update keywords-list members role
 * Note: External users on Semrush workspace keywords lists are not allowed to be invited
 */
export type keywordsListUpdateMembersRole = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: keywordsListUpdateMembersRole_Path;
    headers: keywordsListUpdateMembersRole_Headers;
    cookie: never;
    body: handlers_keywordsListMemberUpdateRoleForm;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * adds members to a keywords list and assigns them a specific role
 * **Note**: External users (without @semrsuh.com email) cannot be invited to keywords lists of Semrush workspaces.
 */
export type keywordsListAddMembers = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: keywordsListAddMembers_Path;
    headers: keywordsListAddMembers_Headers;
    cookie: never;
    body: handlers_keywordListAddMembersForm;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {};
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type keywordsListDeleteMembers_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * basket id
   */
  basket_id: string;
};

export type keywordsListDeleteMembers_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type keywordsListMembers_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * basket id
   */
  basket_id: string;
};

export type keywordsListMembers_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type keywordsListUpdateMembersRole_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * basket id
   */
  basket_id: string;
};

export type keywordsListUpdateMembersRole_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type keywordsListAddMembers_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * basket id
   */
  basket_id: string;
};

export type keywordsListAddMembers_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
