// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { handlers_AdobeAnalyticsWorkspaceConnectionUpdate } from "../../../../../../definitions/handlers.AdobeAnalyticsWorkspaceConnectionUpdate.js";

/**
 * Deprecated: use PUT /v2/workspaces/{workspace_id}/connections/adobe-analytics/{connection_id} with credential_id in body instead.
 * @deprecated
 */
export type adobeAnalyticsConnectionUpdate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: adobeAnalyticsConnectionUpdate_Path;
    headers: adobeAnalyticsConnectionUpdate_Headers;
    cookie: never;
    body: handlers_AdobeAnalyticsWorkspaceConnectionUpdate;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adobeAnalyticsConnectionUpdate_Path = {
  /**
   * workspace id
   */
  workspace_id: string;
  /**
   * connection id
   */
  connection_id: string;
};

export type adobeAnalyticsConnectionUpdate_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
