// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../counterfact-types/index.ts";
import type { http_server_BasicResponse } from "../../../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * This API fetches related tag IDs for the provided keywords.
 * Response has keyword_id mapped to tag ids {"id1":["tag1", "tag2"]}
 */
export type keywordsRelatedTagIdsGet = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: keywordsRelatedTagIdsGet_Path;
    headers: keywordsRelatedTagIdsGet_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { [key: string]: Array<string> };
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type keywordsRelatedTagIdsGet_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * target id
   */
  target_id: string;
};

export type keywordsRelatedTagIdsGet_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
