// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../counterfact-types/index.ts";
import type { handlers_KeywordsTagsRelationsDeleteForm } from "../../../../../../../../../definitions/handlers.KeywordsTagsRelationsDeleteForm.js";
import type { http_server_BasicResponse } from "../../../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * API deletes relantionships of keywords with tags,
 * it can also delete relations of keywords with children and grandchildren of tags if parent id passed
 * expected format of request {"relations": [["keyword_id", "tag_id"]]}
 */
export type keywordsTagsRelationsDelete = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: keywordsTagsRelationsDelete_Path;
    headers: keywordsTagsRelationsDelete_Headers;
    cookie: never;
    body: handlers_KeywordsTagsRelationsDeleteForm;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type keywordsTagsRelationsDelete_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * target id
   */
  target_id: string;
};

export type keywordsTagsRelationsDelete_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
