// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { handlers_WorkspaceConnectionsAttachItem } from "../../../../../definitions/handlers.WorkspaceConnectionsAttachItem.js";

/**
 * Attaches multiple connections to multiple projects in a single transaction.
 */
export type workspaceConnectionsMerge = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: workspaceConnectionsMerge_Path;
    headers: workspaceConnectionsMerge_Headers;
    cookie: never;
    body: Array<handlers_WorkspaceConnectionsAttachItem>;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type workspaceConnectionsMerge_Path = {
  /**
   * workspace id
   */
  workspace_id: string;
};

export type workspaceConnectionsMerge_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
