// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../counterfact-types/index.ts";
import type { handlers_workspaceCheckRolesInAncestryResponse } from "../../../../../../../../definitions/handlers.workspaceCheckRolesInAncestryResponse.js";
import type { http_server_BasicResponse } from "../../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * checks whether user has one of the provided workspace roles in the current workspace or ancestors
 */
export type workspacesCheckRolesInAncestry = (
  $: OmitValueWhenNever<{
    query: workspacesCheckRolesInAncestry_Query;
    querystring: never;
    path: workspacesCheckRolesInAncestry_Path;
    headers: workspacesCheckRolesInAncestry_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceCheckRolesInAncestryResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type workspacesCheckRolesInAncestry_Query = {
  /**
   * roles
   */
  roles: Array<string>;
};

export type workspacesCheckRolesInAncestry_Path = {
  /**
   * user id
   */
  user_id: number;
};

export type workspacesCheckRolesInAncestry_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
