version: 2.1
executors:
  node-java:
    docker:
      - image: cimg/node:18.18-browsers

orbs:
  codecov: codecov/codecov@3.3.0

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node-java
    parallelism: 15

    steps:
      - setup
      - run:
          name: Split package list
          command: circleci tests glob "packages/*" | circleci tests split > /tmp/tests-to-run
      - run:
          name: Lint
          command: cat /tmp/tests-to-run | xargs -I % npm run lint -w %
      - run:
          name: Running tests and getting code coverage
          command: cat /tmp/tests-to-run | xargs -I % npm run test -w %
      - run:
          name: Running integration tests
          command: |
            if grep -q "packages/spacecat-shared-data-access" /tmp/tests-to-run; then
              echo "Running integration tests for spacecat-shared-data-access"
              npm run test:it -w packages/spacecat-shared-data-access
            else
              echo "Skipping integration tests"
            fi
      - codecov/upload
      - run:
          name: Copy test results
          command: |
            mkdir junit
            cat /tmp/tests-to-run | xargs -I % cp %/junit/test-results.xml junit/test-results-$CIRCLE_NODE_INDEX.xml
      - store_test_results:
          path: junit

workflows:
  version: 2
  build:
    jobs:
      - build
