name: "Lint, Test, and Coverage"
description: "Runs lint and test commands, plus coverage"

inputs:
  codecov_token:
    description: "Codecov Token (optional)"
    required: false
    default: ""
  upload_coverage:
    description: "Whether to upload coverage to Codecov (true/false). Default false."
    required: false
    default: "false"
  ecr_pull_role_arn:
    description: "AWS IAM role ARN used to authenticate to private ECR for data-access IT tests."
    required: false
    default: ""
  aws_region:
    description: "AWS region for ECR authentication."
    required: false
    default: "us-east-1"

runs:
  using: "composite"
  steps:
    - name: Lint
      run: npm run lint
      shell: bash

    - name: Check if spacecat-shared-data-access changed
      id: changes
      uses: dorny/paths-filter@v3
      with:
        filters: |
          spacecat-shared:
            - 'packages/spacecat-shared-data-access/**'

    - name: Configure AWS credentials (private ECR pull)
      if: steps.changes.outputs.spacecat-shared == 'true' && inputs.ecr_pull_role_arn != ''
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ inputs.ecr_pull_role_arn }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      if: steps.changes.outputs.spacecat-shared == 'true' && inputs.ecr_pull_role_arn != ''
      uses: aws-actions/amazon-ecr-login@v2

    - name: Run Integration Tests
      if: steps.changes.outputs.spacecat-shared == 'true'
      run: npm run --prefix packages/spacecat-shared-data-access test:it
      shell: bash

    - name: Run Unit Tests
      run: npm run test
      shell: bash

    - name: Upload coverage to Codecov
      if: ${{ inputs.upload_coverage == 'true' }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov_token }}
