name: "Lint, Test, and Coverage"
description: "Runs lint and test commands, plus coverage"

inputs:
  codecov_token:
    description: "Codecov Token (optional)"
    required: false
    default: ""
  upload_coverage:
    description: "Whether to upload coverage to Codecov (true/false). Default false."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Lint
      run: npm run lint
      shell: bash

    - name: Check for IT Tests
      id: check_it_tests
      run: |
        if grep -q "\"test:it\":" package.json; then
          echo "has_it_tests=true" >> $GITHUB_OUTPUT
        else
          echo "has_it_tests=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Run Integration Tests
      run:  npm run --prefix packages/spacecat-shared-data-access test:it
      shell: bash

    - name: Run Unit Tests
      run: npm run test
      shell: bash

    - name: Upload coverage to Codecov
      if: ${{ inputs.upload_coverage == 'true' }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov_token }}
