// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../counterfact-types/index.ts";
import type { http_server_BasicResponse } from "../../../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * This endpoint retrieves limits of specific entities in a workspace and product with respect to a project.
 * It considers project-level constraints, with the draft count for all entities adjusted to align with the project.
 * This enables assessment of how many entities can be added to the project.
 */
export type internalWorkspaceProductLimitsByProject = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: internalWorkspaceProductLimitsByProject_Path;
    headers: internalWorkspaceProductLimitsByProject_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { [key: string]: unknown };
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type internalWorkspaceProductLimitsByProject_Path = {
  /**
   * Unique identifier for the workspace
   */
  id: string;
  /**
   * Unique identifier for the product [enums: seo, aio]
   */
  product_id: string;
  /**
   * Unique identifier for the project
   */
  project_id: string;
};

export type internalWorkspaceProductLimitsByProject_Headers = {
  /**
   * API Key required for authentication
   */
  "API-Key": string;
};
