// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { handlers_workspaceCheckMembershipInAncestryResponse } from "../../../../../../../definitions/handlers.workspaceCheckMembershipInAncestryResponse.js";
import type { http_server_BasicResponse } from "../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * Checks whether the user has membership in the workspace hierarchy (current workspace + descendants).
 * If the optional `membership` query parameter is provided, only those statuses are treated as valid.
 * Valid values: `member`, `guest`, `basic`.
 * If `membership` is omitted, the default behavior is backward compatible: membership is checked by subscription match
 * (`user.SubscriptionID == desc.SubscriptionID`), not by membership status.
 */
export type workspacesCheckMembershipInAncestry = (
  $: OmitValueWhenNever<{
    query: workspacesCheckMembershipInAncestry_Query;
    querystring: never;
    path: workspacesCheckMembershipInAncestry_Path;
    headers: workspacesCheckMembershipInAncestry_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceCheckMembershipInAncestryResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type workspacesCheckMembershipInAncestry_Query = {
  /**
   * Filter by membership status. If provided, only these statuses are considered valid. Allowed: member, guest, basic.
   */
  membership?: Array<string>;
};

export type workspacesCheckMembershipInAncestry_Path = {
  /**
   * workspace id
   */
  userId: number;
};

export type workspacesCheckMembershipInAncestry_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
