// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { handlers_usersCreateForm } from "../../../definitions/handlers.usersCreateForm.js";

/**
 * Creates a new enterprise user based on an existing Semrush user and workspace if provided.
 * Leave workspace as null to create user w/o workspace.
 */
export type usersCreate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: usersCreate_Headers;
    cookie: never;
    body: handlers_usersCreateForm;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      422: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type usersCreate_Headers = {
  /**
   * Admin API key
   */
  "API-Key": string;
};
