// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { handlers_workspacesMembersResponse } from "../../../../../definitions/handlers.workspacesMembersResponse.js";
import type { http_server_BasicResponse } from "../../../../../definitions/http_server.BasicResponse.js";
import type { handlers_workspaceAddMembersForm } from "../../../../../definitions/handlers.workspaceAddMembersForm.js";
import type { handlers_WorkspaceMemberUpsertResponse } from "../../../../../definitions/handlers.WorkspaceMemberUpsertResponse.js";
import type { handlers_workspaceAddMembersResponse } from "../../../../../definitions/handlers.workspaceAddMembersResponse.js";

/**
 * gets a workspace's members
 */
export type internalWorkspacesMembers = (
  $: OmitValueWhenNever<{
    query: internalWorkspacesMembers_Query;
    querystring: never;
    path: internalWorkspacesMembers_Path;
    headers: internalWorkspacesMembers_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspacesMembersResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * internal API to add members to a workspace and assigns them a specific role
 * in response it returns number of user units consumed
 * -ve value means workspace user units are consumed and users are invited to corporate account.
 * 0 values mean user units are not changed and corporate account remains unaffected.
 * **Note**: External users (without @semrsuh.com email) cannot be invited to Semrush workspaces.
 */
export type internalWorkspaceAddMembers = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: internalWorkspaceAddMembers_Path;
    headers: internalWorkspaceAddMembers_Headers;
    cookie: never;
    body: handlers_workspaceAddMembersForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_WorkspaceMemberUpsertResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceAddMembersResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceAddMembersResponse;
          };
        };
        examples: {};
      };
      422: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceAddMembersResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceAddMembersResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type internalWorkspacesMembers_Query = {
  /**
   * page number
   */
  page?: number;
  /**
   * page size
   */
  limit?: number;
  /**
   * asc/desc
   */
  direction?: string;
  /**
   * search by email
   */
  search?: string;
  /**
   * search by role name
   */
  role?: string;
  /**
   * search by membership status
   */
  membership_status?: string;
  /**
   * include parental admins
   */
  include_parental_admins?: boolean;
  /**
   * include parent workspace
   */
  include_parent_workspace?: boolean;
};

export type internalWorkspacesMembers_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type internalWorkspacesMembers_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};

export type internalWorkspaceAddMembers_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type internalWorkspaceAddMembers_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
