// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { handlers_WorkspaceConnectionsResponse } from "../../../../../definitions/handlers.WorkspaceConnectionsResponse.js";

/**
 * Returns a paginated list of workspace connections for service-to-service use (e.g. LFA connector status updater). Same query parameters as the user-facing list endpoint.
 */
export type internalWorkspaceConnectionsList = (
  $: OmitValueWhenNever<{
    query: internalWorkspaceConnectionsList_Query;
    querystring: never;
    path: internalWorkspaceConnectionsList_Path;
    headers: internalWorkspaceConnectionsList_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_WorkspaceConnectionsResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type internalWorkspaceConnectionsList_Query = {
  /**
   * Number of page
   */
  page?: number;
  /**
   * Number of items per page (default: 10)
   */
  limit?: number;
  /**
   * Connection type filter: google-ads, google-analytics, google-console, adobe-analytics, log-file-connector
   */
  type?: string;
  /**
   * Owner filter
   */
  owner_id?: string;
};

export type internalWorkspaceConnectionsList_Path = {
  /**
   * workspace id
   */
  workspace_id: string;
};

export type internalWorkspaceConnectionsList_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
