// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_AdobeCredentialStatusInfo } from "../../../../definitions/handlers.AdobeCredentialStatusInfo.js";

/**
 * Deprecated: use GET /v2/adobe-analytics/status with credential_id in query instead. Gets Adobe credentials status by adobe_proxy_auth_id.
 * @deprecated
 */
export type adobeAnalyticsGetStatus = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: adobeAnalyticsGetStatus_Path;
    headers: adobeAnalyticsGetStatus_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_AdobeCredentialStatusInfo;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adobeAnalyticsGetStatus_Path = {
  /**
   * adobe_proxy_auth_id identifier
   */
  adobe_proxy_auth_id: string;
};

export type adobeAnalyticsGetStatus_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
