// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../counterfact-types/index.ts";
import type { Context } from "../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../counterfact-types/index.ts";
import type { http_server_BasicResponse } from "../../definitions/http_server.BasicResponse.js";

/**
 * this API gets locations from core /get_locations api and pass them in response
 * get_locations api docs can be here(https://kb.semrush.net/display/BlueTeam/locations+get_
 */
export type locations = (
  $: OmitValueWhenNever<{
    query: locations_Query;
    querystring: never;
    path: never;
    headers: locations_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type locations_Query = {
  /**
   * location name(deprecated use q)
   */
  location?: string;
  /**
   * filter by location, alias for location
   */
  q?: string;
  /**
   * location id
   */
  id?: number;
  /**
   * filter by search engine(bing)
   */
  filter_engine?: string;
};

export type locations_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
