// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { handlers_KeywordsListRenameRequest } from "../../../../../definitions/handlers.KeywordsListRenameRequest.js";
import type { handlers_KeywordsListRenameResponse } from "../../../../../definitions/handlers.KeywordsListRenameResponse.js";
import type { http_server_BasicResponse } from "../../../../../definitions/http_server.BasicResponse.js";

/**
 * Rename the name of a keywords-list of the workspace
 */
export type keywordslistsRename = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: keywordslistsRename_Path;
    headers: keywordslistsRename_Headers;
    cookie: never;
    body: handlers_KeywordsListRenameRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_KeywordsListRenameResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type keywordslistsRename_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * id of the keywords-list
   */
  basket_id: number;
};

export type keywordslistsRename_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
