// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { handlers_LogFileAnalysisWorkspaceConnectionPayload } from "../../../../../../../definitions/handlers.LogFileAnalysisWorkspaceConnectionPayload.js";
import type { handlers_WorkspaceConnection } from "../../../../../../../definitions/handlers.WorkspaceConnection.js";

/**
 * Updates an existing Log File Analysis connection using internal API key authentication (e.g. LFA connector status updater). The connection must belong to the workspace and be of type log-file-connector.
 */
export type internalLogFileAnalysisConnectionUpdate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: internalLogFileAnalysisConnectionUpdate_Path;
    headers: internalLogFileAnalysisConnectionUpdate_Headers;
    cookie: never;
    body: handlers_LogFileAnalysisWorkspaceConnectionPayload;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_WorkspaceConnection;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type internalLogFileAnalysisConnectionUpdate_Path = {
  /**
   * workspace id
   */
  workspace_id: string;
  /**
   * connection id
   */
  connection_id: string;
};

export type internalLogFileAnalysisConnectionUpdate_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
