// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_TransactionsListForm } from "../../../../definitions/handlers.TransactionsListForm.js";
import type { handlers_transactionsListResponse } from "../../../../definitions/handlers.transactionsListResponse.js";
import type { http_server_BasicResponse } from "../../../../definitions/http_server.BasicResponse.js";

/**
 * Gets a list of service credits transactions
 */
export type serviceCreditsInternalTransactionsList = (
  $: OmitValueWhenNever<{
    query: serviceCreditsInternalTransactionsList_Query;
    querystring: never;
    path: never;
    headers: serviceCreditsInternalTransactionsList_Headers;
    cookie: never;
    body: handlers_TransactionsListForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_transactionsListResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type serviceCreditsInternalTransactionsList_Query = {
  /**
   * sorting direction
   */
  direction?: string;
  /**
   * sorting field
   */
  field?: string;
  /**
   * page number
   */
  page?: number;
  /**
   * page size
   */
  limit?: number;
};

export type serviceCreditsInternalTransactionsList_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
