// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { handlers_ActivationPanelWorkspaceListResponse } from "../../../../../definitions/handlers.ActivationPanelWorkspaceListResponse.js";
import type { http_server_BasicResponse } from "../../../../../definitions/http_server.BasicResponse.js";

/**
 * lists all organizations workspaces required for Activation Panel. Only first-level workspaces are returned without their limits and children – kept for backward compatibility with organization route.
 */
export type activationPanelGetAllOrganizations = (
  $: OmitValueWhenNever<{
    query: activationPanelGetAllOrganizations_Query;
    querystring: never;
    path: never;
    headers: activationPanelGetAllOrganizations_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_ActivationPanelWorkspaceListResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type activationPanelGetAllOrganizations_Query = {
  /**
   * page number
   */
  page?: number;
  /**
   * page size
   */
  limit?: number;
};

export type activationPanelGetAllOrganizations_Headers = {
  /**
   * Semrush-admin Remote-User (UserId)
   */
  "Remote-User": string;
  /**
   * Admin API key
   */
  "API-Key": string;
};
