// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { handlers_AdobeAnalyticsWorkspaceConnectionCreateV2 } from "../../../../../definitions/handlers.AdobeAnalyticsWorkspaceConnectionCreateV2.js";

/**
 * Creates a new Adobe Analytics connection. Uses credential_id in body; ownership is checked by backend.
 */
export type adobeAnalyticsConnectionCreateV2 = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: adobeAnalyticsConnectionCreateV2_Path;
    headers: adobeAnalyticsConnectionCreateV2_Headers;
    cookie: never;
    body: handlers_AdobeAnalyticsWorkspaceConnectionCreateV2;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adobeAnalyticsConnectionCreateV2_Path = {
  /**
   * workspace id
   */
  workspace_id: string;
};

export type adobeAnalyticsConnectionCreateV2_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
