// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_createWorkspaceV2Form } from "../../../../definitions/handlers.createWorkspaceV2Form.js";
import type { handlers_workspaceResponse } from "../../../../definitions/handlers.workspaceResponse.js";
import type { http_server_BasicResponse } from "../../../../definitions/http_server.BasicResponse.js";

/**
 * Creates a child workspace. If field owner is provided,
 * then the existing user will be the owner of the child workspace,
 * otherwise the virtual owner of this workspace will be created.
 */
export type workspaceChildCreateV2 = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: workspaceChildCreateV2_Path;
    headers: workspaceChildCreateV2_Headers;
    cookie: never;
    body: handlers_createWorkspaceV2Form;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_workspaceResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type workspaceChildCreateV2_Path = {
  /**
   * parent workspace id
   */
  id: string;
};

export type workspaceChildCreateV2_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
