// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_projectV2CreateForm } from "../../../../definitions/handlers.projectV2CreateForm.js";
import type { handlers_projectUpsertResponse } from "../../../../definitions/handlers.projectUpsertResponse.js";
import type { http_server_BasicResponse } from "../../../../definitions/http_server.BasicResponse.js";

export type projectsListV2 = {
  /* error creating export "projectsListV2" for types/paths/v2/workspaces/{id}/projects.types.ts: TypeError: Cannot read properties of undefined (reading 'data')
    at SchemaTypeCoder.writeCode (file:///Users/ntoccane/Desktop/mysticat-workspace/spacecat-shared/node_modules/counterfact/dist/typescript-generator/schema-type-coder.js:106:14)
    at SchemaTypeCoder.write (file:///Users/ntoccane/Desktop/mysticat-workspace/spacecat-shared/node_modules/counterfact/dist/typescript-generator/type-coder.js:7:21)
    at SchemaTypeCoder.arraySchema (file:///Users/ntoccane/Desktop/mysticat-workspace/spacecat-shared/node_modules/counterfact/dist/typescript-generator/schema-type-coder.js:42:90)
    at SchemaTypeCoder.writeType (file:///Users/ntoccane/Desktop/mysticat-workspace/spacecat-shared/node_modules/counterfact/dist/typescript-generator/schema-type-coder.js:66:25)
    at SchemaTypeCoder.writeCode (file:///Users/ntoccane/Desktop/mysticat-workspace/spacecat-shared/node_modules/counterfact/dist/typescript-generator/schema-type-coder.js:119:21)
    at SchemaTypeCoder.write (file:///Users/ntoccane/Desktop/mysticat-workspace/spacecat-shared/node_modules/counterfact/dist/typescript-generator/type-coder.js:7:21)
    at file:///Users/ntoccane/Desktop/mysticat-workspace/spacecat-shared/node_modules/counterfact/dist/typescript-generator/parameters-type-coder.js:29:74
    at Array.map (<anonymous>)
    at ParametersTypeCoder.writeCode (file:///Users/ntoccane/Desktop/mysticat-workspace/spacecat-shared/node_modules/counterfact/dist/typescript-generator/parameters-type-coder.js:20:14)
    at ParametersTypeCoder.write (file:///Users/ntoccane/Desktop/mysticat-workspace/spacecat-shared/node_modules/counterfact/dist/typescript-generator/type-coder.js:7:21) */
};

/**
 * creates a drafted project in a workspace with name and optional domain
 */
export type projectCreateV2 = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: projectCreateV2_Path;
    headers: projectCreateV2_Headers;
    cookie: never;
    body: handlers_projectV2CreateForm;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_projectUpsertResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      409: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type projectCreateV2_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type projectCreateV2_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
