// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_AdobeBulkStatusRequest } from "../../../../definitions/handlers.AdobeBulkStatusRequest.js";
import type { handlers_AdobeBulkStatusResponse } from "../../../../definitions/handlers.AdobeBulkStatusResponse.js";

/**
 * Deprecated: will be removed without replacement. Use GET /v2/adobe-analytics/status per credential_id instead.
 * @deprecated
 */
export type adobeAnalyticsGetBulkStatus = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: adobeAnalyticsGetBulkStatus_Headers;
    cookie: never;
    body: handlers_AdobeBulkStatusRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_AdobeBulkStatusResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adobeAnalyticsGetBulkStatus_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
