// This file is generated by Counterfact. Do not edit manually.
import type { Context } from "../routes/_.context";

interface LoadContextDefinitions {
  /* code generator adds additional signatures here */
  loadContext(path: "/" | `/${string}`): Context;
  loadContext(path: string): Record<string, unknown>;
}

export interface Scenario$ {
  /** Root context, same as loadContext("/") */
  readonly context: Context;
  readonly loadContext: LoadContextDefinitions["loadContext"];
  /** Named route builders stored in the REPL execution context */
  readonly routes: Record<string, unknown>;
  /** Create a new route builder for a given path */
  readonly route: (path: string) => unknown;
}

/** A scenario function that receives the live REPL environment */
export type Scenario = ($: Scenario$) => Promise<void> | void;

/** Interface for Context objects defined in _.context.ts files */
export interface Context$ {
  /** Load a context object for a specific path */
  readonly loadContext: LoadContextDefinitions["loadContext"];
  /** Load a JSON file relative to this file's path */
  readonly readJson: (relativePath: string) => Promise<unknown>;
}
