// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { handlers_TagsTreeResponse } from "../../../../../../../../../../definitions/handlers.TagsTreeResponse.js";
import type { http_server_BasicResponse } from "../../../../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * This API searches tags and returns ancestors tree structure of matched tags.
 * Consider a tree `foo -> bar -> baz -> quack` and searched for `az`
 * then return result would be `foo -> bar -> baz`, to find children of baz use list tags API.
 */
export type projectSearchTreeTags = (
  $: OmitValueWhenNever<{
    query: projectSearchTreeTags_Query;
    querystring: never;
    path: projectSearchTreeTags_Path;
    headers: projectSearchTreeTags_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_TagsTreeResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type projectSearchTreeTags_Query = {
  /**
   * search
   */
  search?: string;
  /**
   * live
   */
  live?: boolean;
};

export type projectSearchTreeTags_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * target id
   */
  target_id: string;
};

export type projectSearchTreeTags_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
