// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { handlers_SegmentListInternalResponse } from "../../../../../../../definitions/handlers.SegmentListInternalResponse.js";
import type { http_server_BasicResponse } from "../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * gets a list of segments that belong to a project.
 * *filters* here is the exact representation of the filters in the pagemanager.
 * **<u>filters representations:</u>**
 * `col` is one of *url, keyword*. Note: *url_list* is represented as *url* in pagemanager.
 * `op` is one of *and, or, eq, neq, begins_with, not_begins_with, ends_with, not_ends_with, contains,
 * not_contains, gt, lt, gte, lte, in*.
 * `value` is string type. It becomes array of string in case of *in* operator as an exceptional case.
 * *Notes*:
 * * *url_list* always has *in* operator. Only zero or one url_list contains in the whole filters object.
 * * *filters* logical operators *and, or* will not have *col, value* and will have nested *filters*.
 * * *filters* logical operators *and, or* will have maximum depth up to 5 levels from the root.
 * * *filters* non-logical operators will have *col, value* and will not have nested *filters*.
 * * *filters* non-logical operators will have maximum 20 leaves in a single filter object.
 */
export type internalProjectSegmentListGet = (
  $: OmitValueWhenNever<{
    query: internalProjectSegmentListGet_Query;
    querystring: never;
    path: internalProjectSegmentListGet_Path;
    headers: internalProjectSegmentListGet_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_SegmentListInternalResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type internalProjectSegmentListGet_Query = {
  /**
   * page number
   */
  page?: number;
  /**
   * page size
   */
  limit?: number;
};

export type internalProjectSegmentListGet_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
};

export type internalProjectSegmentListGet_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
