// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_CoreUser } from "../../../../definitions/handlers.CoreUser.js";

/**
 * Gets a list of users which have expired subscriptions
 */
export type expiredSubscriptionUsers = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: expiredSubscriptionUsers_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<handlers_CoreUser>;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      422: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type expiredSubscriptionUsers_Headers = {
  /**
   * Admin API key
   */
  "API-Key": string;
};
