// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { handlers_Dimension } from "../../../../../definitions/handlers.Dimension.js";

/**
 * Deprecated: use GET /v2/adobe-analytics/dimensions with credential_id, global_company_id, rsid in query instead.
 * @deprecated
 */
export type adobeAnalyticsGetDimensions = (
  $: OmitValueWhenNever<{
    query: adobeAnalyticsGetDimensions_Query;
    querystring: never;
    path: adobeAnalyticsGetDimensions_Path;
    headers: adobeAnalyticsGetDimensions_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<handlers_Dimension>;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adobeAnalyticsGetDimensions_Query = {
  /**
   * Report Suite ID
   */
  rsid: string;
};

export type adobeAnalyticsGetDimensions_Path = {
  /**
   * adobe_proxy_auth_id identifier
   */
  adobe_proxy_auth_id: string;
  /**
   * Adobe global company ID
   */
  global_company_id: string;
};

export type adobeAnalyticsGetDimensions_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
