// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../counterfact-types/index.ts";
import type { handlers_tagsListResponse } from "../../../../../../../../../definitions/handlers.tagsListResponse.js";
import type { http_server_BasicResponse } from "../../../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * searches tags by name and returns matching tags' without their children or parents
 * @deprecated
 */
export type projectSearchListTags = (
  $: OmitValueWhenNever<{
    query: projectSearchListTags_Query;
    querystring: never;
    path: projectSearchListTags_Path;
    headers: projectSearchListTags_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_tagsListResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type projectSearchListTags_Query = {
  /**
   * page number
   */
  page?: number;
  /**
   * page size
   */
  limit?: number;
  /**
   * search
   */
  search?: string;
  /**
   * live
   */
  live?: boolean;
};

export type projectSearchListTags_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * target id
   */
  target_id: string;
};

export type projectSearchListTags_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
