// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { handlers_AdobeCredentialsCreateRequest } from "../../../definitions/handlers.AdobeCredentialsCreateRequest.js";
import type { handlers_AdobeCredentialsInfo } from "../../../definitions/handlers.AdobeCredentialsInfo.js";

/**
 * Deprecated: use POST /v2/adobe-analytics/credentials instead (returns credential_id, not adobe_proxy_auth_id).
 * @deprecated
 */
export type adobeAnalyticsCreateCredentials = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: adobeAnalyticsCreateCredentials_Headers;
    cookie: never;
    body: handlers_AdobeCredentialsCreateRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_AdobeCredentialsInfo;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adobeAnalyticsCreateCredentials_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
