// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { handlers_AdobeReportSuitesResponse } from "../../../../../../definitions/handlers.AdobeReportSuitesResponse.js";

/**
 * Deprecated: use GET /v2/adobe-analytics/reportsuites/paginated with credential_id and global_company_id in query instead.
 * @deprecated
 */
export type adobeAnalyticsGetReportSuitesPaginated = (
  $: OmitValueWhenNever<{
    query: adobeAnalyticsGetReportSuitesPaginated_Query;
    querystring: never;
    path: adobeAnalyticsGetReportSuitesPaginated_Path;
    headers: adobeAnalyticsGetReportSuitesPaginated_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_AdobeReportSuitesResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adobeAnalyticsGetReportSuitesPaginated_Query = {
  /**
   * Number of items per page
   * @default 10
   */
  size?: number;
  /**
   * Page number (1-indexed)
   * @default 1
   */
  page?: number;
};

export type adobeAnalyticsGetReportSuitesPaginated_Path = {
  /**
   * adobe_proxy_auth_id identifier
   */
  adobe_proxy_auth_id: string;
  /**
   * Adobe global company ID
   */
  global_company_id: string;
};

export type adobeAnalyticsGetReportSuitesPaginated_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
