// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { page_engine_backend_internal_usermanager_core_domain_ProductProjectMetadata } from "../../../../../../../definitions/page-engine-backend_internal_usermanager_core_domain.ProductProjectMetadata.js";
import type { http_server_BasicResponse } from "../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * Retrieves a list of projects associated with a product and workspace the user has access to.
 * Requires the `user_id` query parameter to determine the user identity.
 * If the user is not a valid enterprise user, the project list will be empty.
 */
export type internalProductProjectsFind = (
  $: OmitValueWhenNever<{
    query: internalProductProjectsFind_Query;
    querystring: never;
    path: internalProductProjectsFind_Path;
    headers: internalProductProjectsFind_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<page_engine_backend_internal_usermanager_core_domain_ProductProjectMetadata>;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type internalProductProjectsFind_Query = {
  /**
   * Unique identifier for the user
   */
  user_id: number;
};

export type internalProductProjectsFind_Path = {
  /**
   * Unique identifier for the workspace
   */
  id: string;
  /**
   * Unique identifier for the product [possible values: seo, aio]
   */
  product_id: string;
};

export type internalProductProjectsFind_Headers = {
  /**
   * API key for authentication
   */
  "API-Key": string;
};
