// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { handlers_Metric } from "../../../../definitions/handlers.Metric.js";

/**
 * Gets Adobe metrics by internal credential_id with ownership check.
 */
export type adobeAnalyticsGetMetricsV2 = (
  $: OmitValueWhenNever<{
    query: adobeAnalyticsGetMetricsV2_Query;
    querystring: never;
    path: never;
    headers: adobeAnalyticsGetMetricsV2_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<handlers_Metric>;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adobeAnalyticsGetMetricsV2_Query = {
  /**
   * Internal credential ID
   */
  credential_id: number;
  /**
   * Adobe global company ID
   */
  global_company_id: string;
  /**
   * Report Suite ID
   */
  rsid: string;
};

export type adobeAnalyticsGetMetricsV2_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
