// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../counterfact-types/index.ts";
import type { handlers_pagespeedKeywordsDeleteForm } from "../../../../../../../../definitions/handlers.pagespeedKeywordsDeleteForm.js";
import type { http_server_BasicResponse } from "../../../../../../../../definitions/http_server.BasicResponse.js";
import type { handlers_pagespeedKeywordsListResponse } from "../../../../../../../../definitions/handlers.pagespeedKeywordsListResponse.js";
import type { handlers_pagespeedCrawlerAddKeywordsForm } from "../../../../../../../../definitions/handlers.pagespeedCrawlerAddKeywordsForm.js";
import type { handlers_keyword } from "../../../../../../../../definitions/handlers.keyword.js";

/**
 * deletes a list of keywords from pagespeed crawlers
 */
export type pagespeedDeleteKeywords = (
  $: OmitValueWhenNever<{
    query: pagespeedDeleteKeywords_Query;
    querystring: never;
    path: pagespeedDeleteKeywords_Path;
    headers: pagespeedDeleteKeywords_Headers;
    cookie: never;
    body: handlers_pagespeedKeywordsDeleteForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<string>;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * gets a list of keywords of pagespeed crawler that belong to a project
 */
export type pagespeedKeywordsList = (
  $: OmitValueWhenNever<{
    query: pagespeedKeywordsList_Query;
    querystring: never;
    path: pagespeedKeywordsList_Path;
    headers: pagespeedKeywordsList_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_pagespeedKeywordsListResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * adds keywords to pagespeed crawlers
 */
export type pagespeedAddKeywords = (
  $: OmitValueWhenNever<{
    query: pagespeedAddKeywords_Query;
    querystring: never;
    path: pagespeedAddKeywords_Path;
    headers: pagespeedAddKeywords_Headers;
    cookie: never;
    body: handlers_pagespeedCrawlerAddKeywordsForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<handlers_keyword>;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type pagespeedDeleteKeywords_Query = {
  /**
   * live
   */
  live?: boolean;
};

export type pagespeedDeleteKeywords_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * pagespeed crawler id
   */
  crawler_id: string;
};

export type pagespeedDeleteKeywords_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type pagespeedKeywordsList_Query = {
  /**
   * page number
   */
  page?: number;
  /**
   * results offset
   */
  offset?: number;
  /**
   * page size
   */
  limit?: number;
  /**
   * live
   */
  live?: boolean;
};

export type pagespeedKeywordsList_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * pagespeed crawler id
   */
  crawler_id: string;
};

export type pagespeedKeywordsList_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type pagespeedAddKeywords_Query = {
  /**
   * live
   */
  live?: boolean;
};

export type pagespeedAddKeywords_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * pagespeed crawler id
   */
  crawler_id: string;
};

export type pagespeedAddKeywords_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
