// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../counterfact-types/index.ts";
import type { handlers_pagespeedURLsDeleteForm } from "../../../../../../../../definitions/handlers.pagespeedURLsDeleteForm.js";
import type { http_server_BasicResponse } from "../../../../../../../../definitions/http_server.BasicResponse.js";
import type { handlers_pagespeedURLsListResponse } from "../../../../../../../../definitions/handlers.pagespeedURLsListResponse.js";
import type { handlers_pagespeedCrawlerAddURLsForm } from "../../../../../../../../definitions/handlers.pagespeedCrawlerAddURLsForm.js";
import type { handlers_pagespeedURL } from "../../../../../../../../definitions/handlers.pagespeedURL.js";

/**
 * deletes a list of urls from pagespeed crawlers that belong to a project
 */
export type pagespeedDeleteUrls = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: pagespeedDeleteUrls_Path;
    headers: pagespeedDeleteUrls_Headers;
    cookie: never;
    body: handlers_pagespeedURLsDeleteForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<string>;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * gets a list of urls of pagespeed crawler that belong to a project
 */
export type pagespeedUrlsList = (
  $: OmitValueWhenNever<{
    query: pagespeedUrlsList_Query;
    querystring: never;
    path: pagespeedUrlsList_Path;
    headers: pagespeedUrlsList_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_pagespeedURLsListResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * adds a list of urls to pagespeed crawlers that belong to a project
 */
export type pagespeedAddUrls = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: pagespeedAddUrls_Path;
    headers: pagespeedAddUrls_Headers;
    cookie: never;
    body: handlers_pagespeedCrawlerAddURLsForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<handlers_pagespeedURL>;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type pagespeedDeleteUrls_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * pagespeed crawler id
   */
  crawler_id: string;
};

export type pagespeedDeleteUrls_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type pagespeedUrlsList_Query = {
  /**
   * page number
   */
  page?: number;
  /**
   * results offset
   */
  offset?: number;
  /**
   * page size
   */
  limit?: number;
  /**
   * live
   */
  live?: boolean;
};

export type pagespeedUrlsList_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * pagespeed crawler id
   */
  crawler_id: string;
};

export type pagespeedUrlsList_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type pagespeedAddUrls_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * pagespeed crawler id
   */
  crawler_id: string;
};

export type pagespeedAddUrls_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
