// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { http_server_BasicResponse } from "../../../../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * This API download keywords along with preferred URLs and tags associated with keywords.
 * First element is supposed to be keyword name
 * Second element is supposed to be preferred URL
 * Third and subsequent elements are supposed to be list of tags.
 * Tags are expected to be separated by __ notion.
 * All tags are packaged in a quoted-field.
 * Example of a csv row: keyword name, preferred_url, "tag1__tag2__tag3,tag4__tag5__tag6"
 */
export type projectDownloadTaggedKeywords = (
  $: OmitValueWhenNever<{
    query: projectDownloadTaggedKeywords_Query;
    querystring: never;
    path: projectDownloadTaggedKeywords_Path;
    headers: projectDownloadTaggedKeywords_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type projectDownloadTaggedKeywords_Query = {
  /**
   * live
   */
  live?: boolean;
};

export type projectDownloadTaggedKeywords_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * target id
   */
  target_id: string;
};

export type projectDownloadTaggedKeywords_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
