// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { handlers_AdobeAnalyticsValidateRequest } from "../../../../../../definitions/handlers.AdobeAnalyticsValidateRequest.js";
import type { handlers_AdobeAnalyticsValidateResponse } from "../../../../../../definitions/handlers.AdobeAnalyticsValidateResponse.js";

/**
 * Deprecated: use POST /v2/adobe-analytics/credentials/metrics-dimensions/validation with credential_id in body instead.
 * @deprecated
 */
export type adobeAnalyticsValidate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: adobeAnalyticsValidate_Path;
    headers: adobeAnalyticsValidate_Headers;
    cookie: never;
    body: handlers_AdobeAnalyticsValidateRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_AdobeAnalyticsValidateResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type adobeAnalyticsValidate_Path = {
  /**
   * Adobe Proxy Auth ID
   */
  adobe_proxy_auth_id: string;
  /**
   * Global Company ID
   */
  global_company_id: string;
};

export type adobeAnalyticsValidate_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
