# generated by datamodel-codegen:
#   filename:  openapi3.json
#   timestamp: 2026-06-15T17:23:07+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class BasicResponse(BaseModel):
    errors: dict[str, Any] | None = None
    message: str | None = None
