// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../counterfact-types/index.ts";
import type { handlers_adminProjectTransferForm } from "../../../../../../../../definitions/handlers.adminProjectTransferForm.js";
import type { http_server_BasicResponse } from "../../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * Transfers a list of projects from a source workspace to a target workspace. Only AI projects with transferable status can be moved. SEO and SI projects will be marked as failed. The endpoint validates target workspace product enablement, available resource limits (projects, keywords, pages, prompts, pagespeed URLs), and RBAC roles. Users with explicit project roles or workspace roles in the source workspace will be granted appropriate roles in the target workspace. Returns a map of failed project IDs with failure reasons (empty map indicates all projects transferred successfully).
 */
export type activationPanelProjectsTransfer = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: activationPanelProjectsTransfer_Path;
    headers: activationPanelProjectsTransfer_Headers;
    cookie: never;
    body: handlers_adminProjectTransferForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { [key: string]: string };
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      422: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type activationPanelProjectsTransfer_Path = {
  /**
   * Source Workspace ID (UUID)
   */
  id: string;
};

export type activationPanelProjectsTransfer_Headers = {
  /**
   * Semrush-admin Remote-User (UserId)
   */
  "Remote-User": string;
  /**
   * Admin API key
   */
  "API-Key": string;
};
