// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../../counterfact-types/index.ts";
import type { http_server_BasicResponse } from "../../../../../../../../../../definitions/http_server.BasicResponse.js";

/**
 * This API download keywords along with preferred urls associated with keywords.
 * each row represents one keyword and its preferred url and values are expected to be comma
 * separated for csv file. first element is supposed to be keyword name
 * whereas second element is supposed to be preferred urls.
 */
export type keywordsPreferredUrlsDownload = (
  $: OmitValueWhenNever<{
    query: keywordsPreferredUrlsDownload_Query;
    querystring: never;
    path: keywordsPreferredUrlsDownload_Path;
    headers: keywordsPreferredUrlsDownload_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "text/csv": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type keywordsPreferredUrlsDownload_Query = {
  /**
   * live
   */
  live?: boolean;
};

export type keywordsPreferredUrlsDownload_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * target id
   */
  target_id: string;
};

export type keywordsPreferredUrlsDownload_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
