// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { handlers_TransactionsCreateFormV2 } from "../../../definitions/handlers.TransactionsCreateFormV2.js";
import type { page_engine_backend_internal_usermanager_core_domain_Transaction } from "../../../definitions/page-engine-backend_internal_usermanager_core_domain.Transaction.js";
import type { http_server_BasicResponse } from "../../../definitions/http_server.BasicResponse.js";

/**
 * Creates a transaction for service credits and other transacting product limits such as pages of
 * SI product. In order to create service credits transactions set `global_limit_key` to `service_units`,
 * and leave `product_limit` empty.
 * In oder to create pages and other limits' transaction set `product_limit` and leave `global_limit_key` empty
 * otherwise it will not accept the inputs.
 * `owner_id` is required when `global_limit_key` is set to `service_units`.
 * `receipt_id` is also not required when `product_limit` is set.
 */
export type transactionCreateV2 = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: transactionCreateV2_Headers;
    cookie: never;
    body: handlers_TransactionsCreateFormV2;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: page_engine_backend_internal_usermanager_core_domain_Transaction;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      422: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type transactionCreateV2_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
