// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { page_engine_backend_internal_usermanager_core_domain_WorkspaceUpsert } from "../../../../../../definitions/page-engine-backend_internal_usermanager_core_domain.WorkspaceUpsert.js";
import type { http_server_BasicResponse } from "../../../../../../definitions/http_server.BasicResponse.js";

/**
 * updates a workspace matching with id (made for Activation Panel). Title and icon can be updated for any workspace (including child workspaces). Icon can be set to empty string. Product tiers can only be updated for master workspaces (direct children of root workspace).
 */
export type activationPanelWorkspaceUpdate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: activationPanelWorkspaceUpdate_Path;
    headers: activationPanelWorkspaceUpdate_Headers;
    cookie: never;
    body: page_engine_backend_internal_usermanager_core_domain_WorkspaceUpsert;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type activationPanelWorkspaceUpdate_Path = {
  /**
   * workspace id
   */
  id: string;
};

export type activationPanelWorkspaceUpdate_Headers = {
  /**
   * Semrush-admin Remote-User (UserId)
   */
  "Remote-User": string;
  /**
   * Admin API key
   */
  "API-Key": string;
};
