// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { handlers_InternalWorkspaceConnectionDetails } from "../../../../../../definitions/handlers.InternalWorkspaceConnectionDetails.js";

/**
 * Retrieves the details of workspace connection. Returns adobe_proxy_auth_id instead of credential_id for adobe analytics connections.
 */
export type internalWorkspaceConnectionByid = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: internalWorkspaceConnectionByid_Path;
    headers: internalWorkspaceConnectionByid_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_InternalWorkspaceConnectionDetails;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type internalWorkspaceConnectionByid_Path = {
  /**
   * workspace id
   */
  workspace_id: string;
  /**
   * connection id
   */
  connection_id: string;
};

export type internalWorkspaceConnectionByid_Headers = {
  /**
   * API key
   */
  "API-Key": string;
};
