// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { handlers_goalsDeleteForm } from "../../../../../../definitions/handlers.goalsDeleteForm.js";
import type { http_server_BasicResponse } from "../../../../../../definitions/http_server.BasicResponse.js";
import type { handlers_goalsListResponse } from "../../../../../../definitions/handlers.goalsListResponse.js";
import type { handlers_goalsUpsertForm } from "../../../../../../definitions/handlers.goalsUpsertForm.js";
import type { handlers_goalUpsertReponse } from "../../../../../../definitions/handlers.goalUpsertReponse.js";

/**
 * this API deletes multiple goals for a project
 */
export type goalsDelete = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: goalsDelete_Path;
    headers: goalsDelete_Headers;
    cookie: never;
    body: handlers_goalsDeleteForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<string>;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * this API returns list of goals for a project
 */
export type goalsList = (
  $: OmitValueWhenNever<{
    query: goalsList_Query;
    querystring: never;
    path: goalsList_Path;
    headers: goalsList_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_goalsListResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * this API creates a goal for a project
 */
export type goalCreate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: goalCreate_Path;
    headers: goalCreate_Headers;
    cookie: never;
    body: handlers_goalsUpsertForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_goalUpsertReponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type goalsDelete_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
};

export type goalsDelete_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type goalsList_Query = {
  /**
   * live
   */
  live?: boolean;
  /**
   * page number
   */
  page?: number;
  /**
   * limit number
   */
  limit?: number;
};

export type goalsList_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
};

export type goalsList_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type goalCreate_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
};

export type goalCreate_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
