// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { http_server_BasicResponse } from "../../../../../../definitions/http_server.BasicResponse.js";
import type { handlers_targetListResponse } from "../../../../../../definitions/handlers.targetListResponse.js";
import type { handlers_targetCreateForm } from "../../../../../../definitions/handlers.targetCreateForm.js";
import type { handlers_Target } from "../../../../../../definitions/handlers.Target.js";

/**
 * deletes a target
 */
export type projectTargetDelete = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: projectTargetDelete_Path;
    headers: projectTargetDelete_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: unknown;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * gets a list of targets that belong to a project
 */
export type projectTargetListGet = (
  $: OmitValueWhenNever<{
    query: projectTargetListGet_Query;
    querystring: never;
    path: projectTargetListGet_Path;
    headers: projectTargetListGet_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: handlers_targetListResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * creates target of the project
 */
export type projectAddTarget = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: projectAddTarget_Path;
    headers: projectAddTarget_Headers;
    cookie: never;
    body: handlers_targetCreateForm;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<handlers_Target>;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
      500: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: http_server_BasicResponse;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: never;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type projectTargetDelete_Path = {
  /**
   * workspace id
   */
  id: string;
  /**
   * project id
   */
  project_id: string;
  /**
   * target id
   */
  target_id: string;
};

export type projectTargetDelete_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type projectTargetListGet_Query = {
  /**
   * page number
   */
  page?: number;
  /**
   * page size
   */
  limit?: number;
  /**
   * live
   */
  live?: boolean;
};

export type projectTargetListGet_Path = {
  /**
   * workspace id
   * @default "19193849-51bf-413d-9ed9-45a63e649887"
   */
  id: string;
  /**
   * project id
   * @default "95cb3f7d-d932-4d8d-ba81-639731d39c08"
   */
  project_id: string;
};

export type projectTargetListGet_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};

export type projectAddTarget_Path = {
  /**
   * workspace id
   * @default "19193849-51bf-413d-9ed9-45a63e649887"
   */
  id: string;
  /**
   * project id
   * @default "95cb3f7d-d932-4d8d-ba81-639731d39c08"
   */
  project_id: string;
};

export type projectAddTarget_Headers = {
  /**
   * JWT Token
   */
  "Auth-Data-Jwt": string;
};
